spring.application.name=demo
spring.datasource.url=jdbc:h2:file:C:/Projekte/Wedler_Samuel_10245165_ DLBITOWAWBI01/src/main/resources/data/data

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

server.port=8081